POST http://localhost:5000/api/rebuild-character HTTP/1.1
content-type: application/json

{"choices_made":
{
  "Elven Lineage": "Wisdom",
  "Fighting Style": "Archery",
  "Keen Senses": "Survival",
  "ability_scores": {
    "Charisma": 10,
    "Constitution": 13,
    "Dexterity": 15,
    "Intelligence": 8,
    "Strength": 14,
    "Wisdom": 12
  },
  "alignment": "Neutral Good",
  "background": "Soldier",
  "background_bonuses": {
    "Constitution": 1,
    "Dexterity": 2
  },
  "character_name": "Elenian",
  "class": "Fighter",
  "equipment_selections": {
    "background_equipment": "option_a",
    "class_equipment": "option_b"
  },
  "language_choices_needed": 1,
  "languages": [],
  "level": 3,
  "lineage": "Wood Elf",
  "skill_choices": [
    "Acrobatics",
    "Perception"
  ],
  "species": "Elf",
  "subclass": "Champion",
  "weapon_mastery_selections": [
    "Longbow",
    "Greataxe",
    "Longsword"
  ]
}
}