#!/usr/bin/env python3
"""One-off injector: append `multiclassing` block to each class JSON."""
import json
from pathlib import Path

MULTICLASSING = {
    "Barbarian": {"hit_die_granted": 12, "armor_training": ["Shields"], "weapon_training": ["Martial"], "tool_training": [], "skill_proficiencies": None, "saving_throw_proficiencies": [], "other_proficiencies": [], "notes": None, "source_text": "As a Multiclass Character: Gain the following traits from the Core Barbarian Traits table: Hit Point Die, proficiency with Martial weapons, and training with Shields. Gain the Barbarian's level 1 features, which are listed in the Barbarian Features table."},
    "Bard": {"hit_die_granted": 8, "armor_training": ["Light"], "weapon_training": [], "tool_training": ["Musical Instrument (1 of your choice)"], "skill_proficiencies": {"count": 1, "options": "any"}, "saving_throw_proficiencies": [], "other_proficiencies": [], "notes": None, "source_text": "As a Multiclass Character: Gain the following traits from the Core Bard Traits table: Hit Point Die, proficiency in one skill of your choice, proficiency with one Musical Instrument of your choice, and training with Light armor. Gain the Bard's level 1 features, which are listed in the Bard Features table. See the multiclassing rules in multiclassing to determine your available spell slots."},
    "Cleric": {"hit_die_granted": 8, "armor_training": ["Light", "Medium", "Shields"], "weapon_training": [], "tool_training": [], "skill_proficiencies": None, "saving_throw_proficiencies": [], "other_proficiencies": [], "notes": None, "source_text": "As a Multiclass Character: Gain the following traits from the Core Cleric Traits table: Hit Point Die and training with Light and Medium armor and Shields. Gain the Cleric's level 1 features, which are listed in the Cleric Features table. See the multiclassing rules in multiclassing to determine your available spell slots."},
    "Druid": {"hit_die_granted": 8, "armor_training": ["Light", "Shields"], "weapon_training": [], "tool_training": [], "skill_proficiencies": None, "saving_throw_proficiencies": [], "other_proficiencies": [], "notes": None, "source_text": "As a Multiclass Druid: Gain the following traits from the Core Druid Traits table: Hit Point Die and training with Light armor and Shields. Gain the Druid's level 1 features, which are listed in the Druid Features table. See the multiclassing rules in multiclassing to determine your available spell slots."},
    "Fighter": {"hit_die_granted": 10, "armor_training": ["Light", "Medium", "Shields"], "weapon_training": ["Martial"], "tool_training": [], "skill_proficiencies": None, "saving_throw_proficiencies": [], "other_proficiencies": [], "notes": None, "source_text": "As a Multiclass Fighter: Gain the following traits from the Core Fighter Traits table: Hit Point Die, proficiency with Martial weapons, and training with Light and Medium armor and Shields. Gain the Fighter's level 1 features, which are listed in the Fighter Features table."},
    "Monk": {"hit_die_granted": 8, "armor_training": [], "weapon_training": [], "tool_training": [], "skill_proficiencies": None, "saving_throw_proficiencies": [], "other_proficiencies": [], "notes": "Multiclass Monks gain only the Hit Point Die from the Core Monk Traits table (no weapon, armor, or tool proficiencies granted on multiclass entry).", "source_text": "As a Multiclass Monk: Gain the Hit Point Die trait from the Core Monk Traits table. Gain the Monk's level 1 features, which are listed in the Monk Features table."},
    "Paladin": {"hit_die_granted": 10, "armor_training": ["Light", "Medium", "Shields"], "weapon_training": ["Martial"], "tool_training": [], "skill_proficiencies": None, "saving_throw_proficiencies": [], "other_proficiencies": [], "notes": None, "source_text": "As a Multiclass Character: Gain the following traits from the Core Paladin Traits table: Hit Point Die, proficiency with Martial weapons, and training with Light and Medium armor and Shields. Gain the Paladin's level 1 features, which are listed in the Paladin Features table. See the multiclassing rules in multiclassing to determine your available spell slots."},
    "Ranger": {"hit_die_granted": 10, "armor_training": ["Light", "Medium", "Shields"], "weapon_training": ["Martial"], "tool_training": [], "skill_proficiencies": {"count": 1, "options": ["Animal Handling", "Athletics", "Insight", "Investigation", "Nature", "Perception", "Stealth", "Survival"]}, "saving_throw_proficiencies": [], "other_proficiencies": [], "notes": None, "source_text": "As a Multiclass Character: Gain the following traits from the Core Ranger Traits table: Hit Point Die, proficiency with Martial weapons, proficiency in one skill of your choice from the Ranger's skill list, training with Light and Medium Armor and Shields. Gain the Ranger's level 1 features, which are listed in the Ranger Features table. See the multiclassing rules in multiclassing to determine your available spell slots."},
    "Rogue": {"hit_die_granted": 8, "armor_training": ["Light"], "weapon_training": [], "tool_training": ["Thieves' Tools"], "skill_proficiencies": {"count": 1, "options": ["Acrobatics", "Athletics", "Deception", "Insight", "Intimidation", "Investigation", "Perception", "Performance", "Persuasion", "Sleight of Hand", "Stealth"]}, "saving_throw_proficiencies": [], "other_proficiencies": [], "notes": None, "source_text": "As a Multiclass Character: Gain the following traits from the Core Rogue Traits table: Hit Point Die, proficiency in one skill of your choice from the Rogue's skill list, proficiency with Thieves' Tools, and training with Light Armor. Gain the Rogue's level 1 features, which are listed in the Rogue Features table."},
    "Sorcerer": {"hit_die_granted": 6, "armor_training": [], "weapon_training": [], "tool_training": [], "skill_proficiencies": None, "saving_throw_proficiencies": [], "other_proficiencies": [], "notes": None, "source_text": "As a Multiclass Character: Gain the Hit Point Die from the Core Sorcerer Traits table. Gain the Sorcerer's level 1 features, which are listed in the Sorcerer Features table. See the multiclassing rules in multiclassing to determine your available spell slots."},
    "Warlock": {"hit_die_granted": 8, "armor_training": ["Light"], "weapon_training": [], "tool_training": [], "skill_proficiencies": None, "saving_throw_proficiencies": [], "other_proficiencies": [], "notes": None, "source_text": "As a Multiclass Character: Gain the following traits from the Core Warlock Traits table: Hit Point Die and training with Light Armor. Gain the Warlock's level 1 features, which are listed in the Warlock Features table. See the multiclassing rules in multiclassing to determine your available spell slots."},
    "Wizard": {"hit_die_granted": 6, "armor_training": [], "weapon_training": [], "tool_training": [], "skill_proficiencies": None, "saving_throw_proficiencies": [], "other_proficiencies": [], "notes": None, "source_text": "As a Multiclass Character: Gain the Hit Point Die from the Core Wizard Traits table. Gain the Wizard's level 1 features, which are listed in the Wizard Features table. See the multiclassing rules in multiclassing to determine your available spell slots."},
}

CLASSES_DIR = Path(__file__).resolve().parent.parent / "data" / "classes"

for name, block in MULTICLASSING.items():
    path = CLASSES_DIR / f"{name.lower()}.json"
    with open(path) as f:
        data = json.load(f)
    # Remove if present so re-runs are idempotent, then append at end.
    data.pop("multiclassing", None)
    data["multiclassing"] = block
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    print(f"Updated {path.name}")
